sudo: false
language: node_js
node_js:
    - "0.10"
branches:
    only:
        - release
cache:
    directories:
        - node_modules
before_script:
    - npm run compile
    - npm run build
after_success:
    - cat coverage/lcov.info | coveralls
